/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AudioRecap = IDL.Record({
  'id' : IDL.Nat,
  'durationSecs' : IDL.Nat,
  'audioStorageKey' : IDL.Text,
  'tradeId' : IDL.Nat,
  'recordedAtNs' : IDL.Int,
  'transcript' : IDL.Text,
});
export const MediaType = IDL.Variant({
  'gif' : IDL.Null,
  'videoClip' : IDL.Null,
  'annotatedImage' : IDL.Null,
  'screenshot' : IDL.Null,
});
export const ChartMetadata = IDL.Record({
  'timeframe' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Float64),
  'symbol' : IDL.Opt(IDL.Text),
});
export const Media = IDL.Record({
  'id' : IDL.Nat,
  'uploadedAtNs' : IDL.Int,
  'source' : IDL.Variant({
    'userUpload' : IDL.Null,
    'chromeExtension' : IDL.Null,
  }),
  'tradeId' : IDL.Nat,
  'originalStorageKey' : IDL.Opt(IDL.Text),
  'storageKey' : IDL.Text,
  'caption' : IDL.Opt(IDL.Text),
  'mediaType' : MediaType,
  'chartMetadata' : IDL.Opt(ChartMetadata),
});
export const SkippedTrade = IDL.Record({
  'id' : IDL.Nat,
  'skippedAtNs' : IDL.Int,
  'fomoTagged' : IDL.Bool,
  'owner' : IDL.Principal,
  'note' : IDL.Text,
  'theoreticalPnl' : IDL.Opt(IDL.Float64),
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Direction = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
export const TradeOrigin = IDL.Variant({
  'sociallyInfluenced' : IDL.Null,
  'selfGenerated' : IDL.Null,
});
export const EmotionalState = IDL.Variant({
  'greedy' : IDL.Null,
  'fearful' : IDL.Null,
  'anxious' : IDL.Null,
  'calm' : IDL.Null,
  'euphoric' : IDL.Null,
  'neutral' : IDL.Null,
});
export const EmotionalSnapshot = IDL.Record({
  'note' : IDL.Text,
  'state' : EmotionalState,
  'capturedAtNs' : IDL.Int,
});
export const CounterReason = IDL.Record({ 'text' : IDL.Text });
export const PreTradeThesis = IDL.Record({
  'thesis' : IDL.Text,
  'counterReasons' : IDL.Vec(CounterReason),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DailyTradeSummary = IDL.Record({
  'direction' : Direction,
  'enteredAtNs' : IDL.Int,
  'confidenceRating' : IDL.Nat,
  'bearCasePresent' : IDL.Bool,
  'tradeId' : IDL.Nat,
  'realizedPnl' : IDL.Opt(IDL.Float64),
  'symbol' : IDL.Text,
});
export const ConfidenceOutcomeAnalysis = IDL.Record({
  'overconfidenceFlag' : IDL.Bool,
  'correlation' : IDL.Float64,
});
export const HoldTimeAnalysis = IDL.Record({
  'avgLoserHoldSecs' : IDL.Opt(IDL.Nat),
  'avgWinnerHoldSecs' : IDL.Opt(IDL.Nat),
  'lossAversionFlag' : IDL.Bool,
});
export const StrategyBaselineAnalysis = IDL.Record({
  'statusQuoBiasFlag' : IDL.Bool,
  'historicalWinRate' : IDL.Opt(IDL.Float64),
  'winRate' : IDL.Float64,
  'historicalProfitFactor' : IDL.Opt(IDL.Float64),
  'profitFactor' : IDL.Float64,
});
export const BiasSignatureType = IDL.Variant({
  'confirmationBias' : IDL.Null,
  'herdMentality' : IDL.Null,
  'statusQuoBias' : IDL.Null,
  'dispositionEffect' : IDL.Null,
  'fomoRegret' : IDL.Null,
  'overconfidence' : IDL.Null,
  'lossAversion' : IDL.Null,
  'hotHandFallacy' : IDL.Null,
});
export const BiasCategoryCount = IDL.Record({
  'count' : IDL.Nat,
  'type' : BiasSignatureType,
  'preventableLossEstimate' : IDL.Float64,
});
export const SelfAssessment = IDL.Record({
  'categorizedTrades' : IDL.Vec(BiasCategoryCount),
  'topBiases' : IDL.Vec(BiasSignatureType),
  'progressTo20' : IDL.Nat,
  'progressTo50' : IDL.Nat,
});
export const TargetedFix = IDL.Record({
  'type' : BiasSignatureType,
  'suggestion' : IDL.Text,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'exitAtNs' : IDL.Opt(IDL.Int),
  'entryAtNs' : IDL.Int,
  'direction' : Direction,
  'updatedAtNs' : IDL.Int,
  'tradeOrigin' : TradeOrigin,
  'owner' : IDL.Principal,
  'createdAtNs' : IDL.Int,
  'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
  'confidenceRating' : IDL.Nat,
  'originSourceNote' : IDL.Opt(IDL.Text),
  'positionSize' : IDL.Float64,
  'isDraft' : IDL.Bool,
  'preTradeThesis' : PreTradeThesis,
  'realizedPnl' : IDL.Opt(IDL.Float64),
  'shareableUrl' : IDL.Opt(IDL.Text),
  'entryPrice' : IDL.Float64,
  'preSessionEmotion' : EmotionalSnapshot,
  'exitPrice' : IDL.Opt(IDL.Float64),
  'holdTimeSecs' : IDL.Opt(IDL.Nat),
  'symbol' : IDL.Text,
  'outcomeReasoning' : IDL.Opt(IDL.Text),
});
export const BiasSignature = IDL.Record({
  'tradeIds' : IDL.Vec(IDL.Nat),
  'type' : BiasSignatureType,
  'description' : IDL.Text,
});
export const TradeListFilter = IDL.Record({
  'sortBy' : IDL.Variant({
    'dateAsc' : IDL.Null,
    'pnlAsc' : IDL.Null,
    'pnlDesc' : IDL.Null,
    'dateDesc' : IDL.Null,
  }),
  'dateFromNs' : IDL.Opt(IDL.Int),
  'emotionalState' : IDL.Opt(EmotionalState),
  'symbolQuery' : IDL.Opt(IDL.Text),
  'dateToNs' : IDL.Opt(IDL.Int),
  'originTag' : IDL.Opt(TradeOrigin),
});
export const ExtensionCapture = IDL.Record({
  'direction' : IDL.Opt(Direction),
  'token' : IDL.Text,
  'timeframe' : IDL.Opt(IDL.Text),
  'outcomeNotes' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Float64),
  'realizedPnl' : IDL.Opt(IDL.Float64),
  'caption' : IDL.Opt(IDL.Text),
  'mediaType' : MediaType,
  'entryPrice' : IDL.Opt(IDL.Float64),
  'targetTradeId' : IDL.Opt(IDL.Nat),
  'price' : IDL.Opt(IDL.Float64),
  'exitPrice' : IDL.Opt(IDL.Float64),
  'mediaStorageKey' : IDL.Text,
  'symbol' : IDL.Opt(IDL.Text),
});
export const CaptureResult = IDL.Record({
  'tradeId' : IDL.Nat,
  'wasDraftCreated' : IDL.Bool,
  'mediaId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAudioRecapToTrade' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'durationSecs' : IDL.Nat,
          'audioStorageKey' : IDL.Text,
          'transcript' : IDL.Text,
        }),
      ],
      [AudioRecap],
      [],
    ),
  'addMediaToTrade' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'originalStorageKey' : IDL.Opt(IDL.Text),
          'storageKey' : IDL.Text,
          'caption' : IDL.Opt(IDL.Text),
          'mediaType' : MediaType,
          'chartMetadata' : IDL.Opt(ChartMetadata),
        }),
      ],
      [Media],
      [],
    ),
  'addSkippedTrade' : IDL.Func(
      [
        IDL.Record({
          'fomoTagged' : IDL.Bool,
          'note' : IDL.Text,
          'theoreticalPnl' : IDL.Opt(IDL.Float64),
          'symbol' : IDL.Text,
        }),
      ],
      [SkippedTrade],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrade' : IDL.Func(
      [
        IDL.Record({
          'exitAtNs' : IDL.Opt(IDL.Int),
          'entryAtNs' : IDL.Int,
          'direction' : Direction,
          'tradeOrigin' : TradeOrigin,
          'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
          'confidenceRating' : IDL.Nat,
          'originSourceNote' : IDL.Opt(IDL.Text),
          'positionSize' : IDL.Float64,
          'isDraft' : IDL.Bool,
          'preTradeThesis' : PreTradeThesis,
          'realizedPnl' : IDL.Opt(IDL.Float64),
          'entryPrice' : IDL.Float64,
          'preSessionEmotion' : EmotionalSnapshot,
          'exitPrice' : IDL.Opt(IDL.Float64),
          'symbol' : IDL.Text,
          'outcomeReasoning' : IDL.Opt(IDL.Text),
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteMedia' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteTrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'generateApiToken' : IDL.Func([], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySummary' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(DailyTradeSummary)],
      ['query'],
    ),
  'getMonthlyConfidenceOutcome' : IDL.Func(
      [IDL.Int, IDL.Int],
      [ConfidenceOutcomeAnalysis],
      ['query'],
    ),
  'getMonthlyFomoAnalysis' : IDL.Func(
      [IDL.Int, IDL.Int],
      [
        IDL.Record({
          'fomoTaggedTradeIds' : IDL.Vec(IDL.Nat),
          'skippedTrades' : IDL.Vec(SkippedTrade),
          'theoreticalPnlTotal' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMonthlyHoldTimeAnalysis' : IDL.Func(
      [IDL.Int, IDL.Int],
      [HoldTimeAnalysis],
      ['query'],
    ),
  'getMonthlyStrategyBaseline' : IDL.Func(
      [IDL.Int, IDL.Int],
      [StrategyBaselineAnalysis],
      ['query'],
    ),
  'getSelfAssessment' : IDL.Func([], [SelfAssessment], ['query']),
  'getTargetedFixes' : IDL.Func(
      [IDL.Vec(BiasSignatureType)],
      [IDL.Vec(TargetedFix)],
      ['query'],
    ),
  'getTrade' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
  'getWeeklySignatures' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(BiasSignature)],
      ['query'],
    ),
  'hasApiToken' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAudioRecapsForTrade' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AudioRecap)],
      ['query'],
    ),
  'listMediaForTrade' : IDL.Func([IDL.Nat], [IDL.Vec(Media)], ['query']),
  'listSkippedTrades' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(SkippedTrade) })],
      ['query'],
    ),
  'listTrades' : IDL.Func(
      [TradeListFilter, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(Trade) })],
      ['query'],
    ),
  'receiveExtensionCapture' : IDL.Func([ExtensionCapture], [CaptureResult], []),
  'regenerateApiToken' : IDL.Func([], [IDL.Text], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateTrade' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'exitAtNs' : IDL.Opt(IDL.Int),
          'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
          'confidenceRating' : IDL.Opt(IDL.Nat),
          'isDraft' : IDL.Opt(IDL.Bool),
          'realizedPnl' : IDL.Opt(IDL.Float64),
          'exitPrice' : IDL.Opt(IDL.Float64),
          'outcomeReasoning' : IDL.Opt(IDL.Text),
        }),
      ],
      [Trade],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AudioRecap = IDL.Record({
    'id' : IDL.Nat,
    'durationSecs' : IDL.Nat,
    'audioStorageKey' : IDL.Text,
    'tradeId' : IDL.Nat,
    'recordedAtNs' : IDL.Int,
    'transcript' : IDL.Text,
  });
  const MediaType = IDL.Variant({
    'gif' : IDL.Null,
    'videoClip' : IDL.Null,
    'annotatedImage' : IDL.Null,
    'screenshot' : IDL.Null,
  });
  const ChartMetadata = IDL.Record({
    'timeframe' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Float64),
    'symbol' : IDL.Opt(IDL.Text),
  });
  const Media = IDL.Record({
    'id' : IDL.Nat,
    'uploadedAtNs' : IDL.Int,
    'source' : IDL.Variant({
      'userUpload' : IDL.Null,
      'chromeExtension' : IDL.Null,
    }),
    'tradeId' : IDL.Nat,
    'originalStorageKey' : IDL.Opt(IDL.Text),
    'storageKey' : IDL.Text,
    'caption' : IDL.Opt(IDL.Text),
    'mediaType' : MediaType,
    'chartMetadata' : IDL.Opt(ChartMetadata),
  });
  const SkippedTrade = IDL.Record({
    'id' : IDL.Nat,
    'skippedAtNs' : IDL.Int,
    'fomoTagged' : IDL.Bool,
    'owner' : IDL.Principal,
    'note' : IDL.Text,
    'theoreticalPnl' : IDL.Opt(IDL.Float64),
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Direction = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const TradeOrigin = IDL.Variant({
    'sociallyInfluenced' : IDL.Null,
    'selfGenerated' : IDL.Null,
  });
  const EmotionalState = IDL.Variant({
    'greedy' : IDL.Null,
    'fearful' : IDL.Null,
    'anxious' : IDL.Null,
    'calm' : IDL.Null,
    'euphoric' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const EmotionalSnapshot = IDL.Record({
    'note' : IDL.Text,
    'state' : EmotionalState,
    'capturedAtNs' : IDL.Int,
  });
  const CounterReason = IDL.Record({ 'text' : IDL.Text });
  const PreTradeThesis = IDL.Record({
    'thesis' : IDL.Text,
    'counterReasons' : IDL.Vec(CounterReason),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DailyTradeSummary = IDL.Record({
    'direction' : Direction,
    'enteredAtNs' : IDL.Int,
    'confidenceRating' : IDL.Nat,
    'bearCasePresent' : IDL.Bool,
    'tradeId' : IDL.Nat,
    'realizedPnl' : IDL.Opt(IDL.Float64),
    'symbol' : IDL.Text,
  });
  const ConfidenceOutcomeAnalysis = IDL.Record({
    'overconfidenceFlag' : IDL.Bool,
    'correlation' : IDL.Float64,
  });
  const HoldTimeAnalysis = IDL.Record({
    'avgLoserHoldSecs' : IDL.Opt(IDL.Nat),
    'avgWinnerHoldSecs' : IDL.Opt(IDL.Nat),
    'lossAversionFlag' : IDL.Bool,
  });
  const StrategyBaselineAnalysis = IDL.Record({
    'statusQuoBiasFlag' : IDL.Bool,
    'historicalWinRate' : IDL.Opt(IDL.Float64),
    'winRate' : IDL.Float64,
    'historicalProfitFactor' : IDL.Opt(IDL.Float64),
    'profitFactor' : IDL.Float64,
  });
  const BiasSignatureType = IDL.Variant({
    'confirmationBias' : IDL.Null,
    'herdMentality' : IDL.Null,
    'statusQuoBias' : IDL.Null,
    'dispositionEffect' : IDL.Null,
    'fomoRegret' : IDL.Null,
    'overconfidence' : IDL.Null,
    'lossAversion' : IDL.Null,
    'hotHandFallacy' : IDL.Null,
  });
  const BiasCategoryCount = IDL.Record({
    'count' : IDL.Nat,
    'type' : BiasSignatureType,
    'preventableLossEstimate' : IDL.Float64,
  });
  const SelfAssessment = IDL.Record({
    'categorizedTrades' : IDL.Vec(BiasCategoryCount),
    'topBiases' : IDL.Vec(BiasSignatureType),
    'progressTo20' : IDL.Nat,
    'progressTo50' : IDL.Nat,
  });
  const TargetedFix = IDL.Record({
    'type' : BiasSignatureType,
    'suggestion' : IDL.Text,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'exitAtNs' : IDL.Opt(IDL.Int),
    'entryAtNs' : IDL.Int,
    'direction' : Direction,
    'updatedAtNs' : IDL.Int,
    'tradeOrigin' : TradeOrigin,
    'owner' : IDL.Principal,
    'createdAtNs' : IDL.Int,
    'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
    'confidenceRating' : IDL.Nat,
    'originSourceNote' : IDL.Opt(IDL.Text),
    'positionSize' : IDL.Float64,
    'isDraft' : IDL.Bool,
    'preTradeThesis' : PreTradeThesis,
    'realizedPnl' : IDL.Opt(IDL.Float64),
    'shareableUrl' : IDL.Opt(IDL.Text),
    'entryPrice' : IDL.Float64,
    'preSessionEmotion' : EmotionalSnapshot,
    'exitPrice' : IDL.Opt(IDL.Float64),
    'holdTimeSecs' : IDL.Opt(IDL.Nat),
    'symbol' : IDL.Text,
    'outcomeReasoning' : IDL.Opt(IDL.Text),
  });
  const BiasSignature = IDL.Record({
    'tradeIds' : IDL.Vec(IDL.Nat),
    'type' : BiasSignatureType,
    'description' : IDL.Text,
  });
  const TradeListFilter = IDL.Record({
    'sortBy' : IDL.Variant({
      'dateAsc' : IDL.Null,
      'pnlAsc' : IDL.Null,
      'pnlDesc' : IDL.Null,
      'dateDesc' : IDL.Null,
    }),
    'dateFromNs' : IDL.Opt(IDL.Int),
    'emotionalState' : IDL.Opt(EmotionalState),
    'symbolQuery' : IDL.Opt(IDL.Text),
    'dateToNs' : IDL.Opt(IDL.Int),
    'originTag' : IDL.Opt(TradeOrigin),
  });
  const ExtensionCapture = IDL.Record({
    'direction' : IDL.Opt(Direction),
    'token' : IDL.Text,
    'timeframe' : IDL.Opt(IDL.Text),
    'outcomeNotes' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Float64),
    'realizedPnl' : IDL.Opt(IDL.Float64),
    'caption' : IDL.Opt(IDL.Text),
    'mediaType' : MediaType,
    'entryPrice' : IDL.Opt(IDL.Float64),
    'targetTradeId' : IDL.Opt(IDL.Nat),
    'price' : IDL.Opt(IDL.Float64),
    'exitPrice' : IDL.Opt(IDL.Float64),
    'mediaStorageKey' : IDL.Text,
    'symbol' : IDL.Opt(IDL.Text),
  });
  const CaptureResult = IDL.Record({
    'tradeId' : IDL.Nat,
    'wasDraftCreated' : IDL.Bool,
    'mediaId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAudioRecapToTrade' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'durationSecs' : IDL.Nat,
            'audioStorageKey' : IDL.Text,
            'transcript' : IDL.Text,
          }),
        ],
        [AudioRecap],
        [],
      ),
    'addMediaToTrade' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'originalStorageKey' : IDL.Opt(IDL.Text),
            'storageKey' : IDL.Text,
            'caption' : IDL.Opt(IDL.Text),
            'mediaType' : MediaType,
            'chartMetadata' : IDL.Opt(ChartMetadata),
          }),
        ],
        [Media],
        [],
      ),
    'addSkippedTrade' : IDL.Func(
        [
          IDL.Record({
            'fomoTagged' : IDL.Bool,
            'note' : IDL.Text,
            'theoreticalPnl' : IDL.Opt(IDL.Float64),
            'symbol' : IDL.Text,
          }),
        ],
        [SkippedTrade],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrade' : IDL.Func(
        [
          IDL.Record({
            'exitAtNs' : IDL.Opt(IDL.Int),
            'entryAtNs' : IDL.Int,
            'direction' : Direction,
            'tradeOrigin' : TradeOrigin,
            'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
            'confidenceRating' : IDL.Nat,
            'originSourceNote' : IDL.Opt(IDL.Text),
            'positionSize' : IDL.Float64,
            'isDraft' : IDL.Bool,
            'preTradeThesis' : PreTradeThesis,
            'realizedPnl' : IDL.Opt(IDL.Float64),
            'entryPrice' : IDL.Float64,
            'preSessionEmotion' : EmotionalSnapshot,
            'exitPrice' : IDL.Opt(IDL.Float64),
            'symbol' : IDL.Text,
            'outcomeReasoning' : IDL.Opt(IDL.Text),
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteMedia' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteTrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'generateApiToken' : IDL.Func([], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySummary' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(DailyTradeSummary)],
        ['query'],
      ),
    'getMonthlyConfidenceOutcome' : IDL.Func(
        [IDL.Int, IDL.Int],
        [ConfidenceOutcomeAnalysis],
        ['query'],
      ),
    'getMonthlyFomoAnalysis' : IDL.Func(
        [IDL.Int, IDL.Int],
        [
          IDL.Record({
            'fomoTaggedTradeIds' : IDL.Vec(IDL.Nat),
            'skippedTrades' : IDL.Vec(SkippedTrade),
            'theoreticalPnlTotal' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMonthlyHoldTimeAnalysis' : IDL.Func(
        [IDL.Int, IDL.Int],
        [HoldTimeAnalysis],
        ['query'],
      ),
    'getMonthlyStrategyBaseline' : IDL.Func(
        [IDL.Int, IDL.Int],
        [StrategyBaselineAnalysis],
        ['query'],
      ),
    'getSelfAssessment' : IDL.Func([], [SelfAssessment], ['query']),
    'getTargetedFixes' : IDL.Func(
        [IDL.Vec(BiasSignatureType)],
        [IDL.Vec(TargetedFix)],
        ['query'],
      ),
    'getTrade' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
    'getWeeklySignatures' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(BiasSignature)],
        ['query'],
      ),
    'hasApiToken' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAudioRecapsForTrade' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AudioRecap)],
        ['query'],
      ),
    'listMediaForTrade' : IDL.Func([IDL.Nat], [IDL.Vec(Media)], ['query']),
    'listSkippedTrades' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(SkippedTrade) })],
        ['query'],
      ),
    'listTrades' : IDL.Func(
        [TradeListFilter, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(Trade) })],
        ['query'],
      ),
    'receiveExtensionCapture' : IDL.Func(
        [ExtensionCapture],
        [CaptureResult],
        [],
      ),
    'regenerateApiToken' : IDL.Func([], [IDL.Text], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateTrade' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'exitAtNs' : IDL.Opt(IDL.Int),
            'duringTradeEmotion' : IDL.Opt(EmotionalSnapshot),
            'confidenceRating' : IDL.Opt(IDL.Nat),
            'isDraft' : IDL.Opt(IDL.Bool),
            'realizedPnl' : IDL.Opt(IDL.Float64),
            'exitPrice' : IDL.Opt(IDL.Float64),
            'outcomeReasoning' : IDL.Opt(IDL.Text),
          }),
        ],
        [Trade],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };