/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioRecap {
  'id' : bigint,
  'durationSecs' : bigint,
  'audioStorageKey' : string,
  'tradeId' : bigint,
  'recordedAtNs' : bigint,
  'transcript' : string,
}
export interface BiasCategoryCount {
  'count' : bigint,
  'type' : BiasSignatureType,
  'preventableLossEstimate' : number,
}
export interface BiasSignature {
  'tradeIds' : Array<bigint>,
  'type' : BiasSignatureType,
  'description' : string,
}
export type BiasSignatureType = { 'confirmationBias' : null } |
  { 'herdMentality' : null } |
  { 'statusQuoBias' : null } |
  { 'dispositionEffect' : null } |
  { 'fomoRegret' : null } |
  { 'overconfidence' : null } |
  { 'lossAversion' : null } |
  { 'hotHandFallacy' : null };
export interface CaptureResult {
  'tradeId' : bigint,
  'wasDraftCreated' : boolean,
  'mediaId' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChartMetadata {
  'timeframe' : [] | [string],
  'price' : [] | [number],
  'symbol' : [] | [string],
}
export interface ConfidenceOutcomeAnalysis {
  'overconfidenceFlag' : boolean,
  'correlation' : number,
}
export interface CounterReason { 'text' : string }
export interface DailyTradeSummary {
  'direction' : Direction,
  'enteredAtNs' : bigint,
  'confidenceRating' : bigint,
  'bearCasePresent' : boolean,
  'tradeId' : bigint,
  'realizedPnl' : [] | [number],
  'symbol' : string,
}
export type Direction = { 'long' : null } |
  { 'short' : null };
export interface EmotionalSnapshot {
  'note' : string,
  'state' : EmotionalState,
  'capturedAtNs' : bigint,
}
export type EmotionalState = { 'greedy' : null } |
  { 'fearful' : null } |
  { 'anxious' : null } |
  { 'calm' : null } |
  { 'euphoric' : null } |
  { 'neutral' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExtensionCapture {
  'direction' : [] | [Direction],
  'token' : string,
  'timeframe' : [] | [string],
  'outcomeNotes' : [] | [string],
  'size' : [] | [number],
  'realizedPnl' : [] | [number],
  'caption' : [] | [string],
  'mediaType' : MediaType,
  'entryPrice' : [] | [number],
  'targetTradeId' : [] | [bigint],
  'price' : [] | [number],
  'exitPrice' : [] | [number],
  'mediaStorageKey' : string,
  'symbol' : [] | [string],
}
export interface HoldTimeAnalysis {
  'avgLoserHoldSecs' : [] | [bigint],
  'avgWinnerHoldSecs' : [] | [bigint],
  'lossAversionFlag' : boolean,
}
export interface Media {
  'id' : bigint,
  'uploadedAtNs' : bigint,
  'source' : { 'userUpload' : null } |
    { 'chromeExtension' : null },
  'tradeId' : bigint,
  'originalStorageKey' : [] | [string],
  'storageKey' : string,
  'caption' : [] | [string],
  'mediaType' : MediaType,
  'chartMetadata' : [] | [ChartMetadata],
}
export type MediaType = { 'gif' : null } |
  { 'videoClip' : null } |
  { 'annotatedImage' : null } |
  { 'screenshot' : null };
export interface PreTradeThesis {
  'thesis' : string,
  'counterReasons' : Array<CounterReason>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SelfAssessment {
  'categorizedTrades' : Array<BiasCategoryCount>,
  'topBiases' : Array<BiasSignatureType>,
  'progressTo20' : bigint,
  'progressTo50' : bigint,
}
export interface SkippedTrade {
  'id' : bigint,
  'skippedAtNs' : bigint,
  'fomoTagged' : boolean,
  'owner' : Principal,
  'note' : string,
  'theoreticalPnl' : [] | [number],
  'symbol' : string,
}
export interface StrategyBaselineAnalysis {
  'statusQuoBiasFlag' : boolean,
  'historicalWinRate' : [] | [number],
  'winRate' : number,
  'historicalProfitFactor' : [] | [number],
  'profitFactor' : number,
}
export interface TargetedFix {
  'type' : BiasSignatureType,
  'suggestion' : string,
}
export interface Trade {
  'id' : bigint,
  'exitAtNs' : [] | [bigint],
  'entryAtNs' : bigint,
  'direction' : Direction,
  'updatedAtNs' : bigint,
  'tradeOrigin' : TradeOrigin,
  'owner' : Principal,
  'createdAtNs' : bigint,
  'duringTradeEmotion' : [] | [EmotionalSnapshot],
  'confidenceRating' : bigint,
  'originSourceNote' : [] | [string],
  'positionSize' : number,
  'isDraft' : boolean,
  'preTradeThesis' : PreTradeThesis,
  'realizedPnl' : [] | [number],
  'shareableUrl' : [] | [string],
  'entryPrice' : number,
  'preSessionEmotion' : EmotionalSnapshot,
  'exitPrice' : [] | [number],
  'holdTimeSecs' : [] | [bigint],
  'symbol' : string,
  'outcomeReasoning' : [] | [string],
}
export interface TradeListFilter {
  'sortBy' : { 'dateAsc' : null } |
    { 'pnlAsc' : null } |
    { 'pnlDesc' : null } |
    { 'dateDesc' : null },
  'dateFromNs' : [] | [bigint],
  'emotionalState' : [] | [EmotionalState],
  'symbolQuery' : [] | [string],
  'dateToNs' : [] | [bigint],
  'originTag' : [] | [TradeOrigin],
}
export type TradeOrigin = { 'sociallyInfluenced' : null } |
  { 'selfGenerated' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addAudioRecapToTrade' : ActorMethod<
    [
      bigint,
      {
        'durationSecs' : bigint,
        'audioStorageKey' : string,
        'transcript' : string,
      },
    ],
    AudioRecap
  >,
  'addMediaToTrade' : ActorMethod<
    [
      bigint,
      {
        'originalStorageKey' : [] | [string],
        'storageKey' : string,
        'caption' : [] | [string],
        'mediaType' : MediaType,
        'chartMetadata' : [] | [ChartMetadata],
      },
    ],
    Media
  >,
  'addSkippedTrade' : ActorMethod<
    [
      {
        'fomoTagged' : boolean,
        'note' : string,
        'theoreticalPnl' : [] | [number],
        'symbol' : string,
      },
    ],
    SkippedTrade
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTrade' : ActorMethod<
    [
      {
        'exitAtNs' : [] | [bigint],
        'entryAtNs' : bigint,
        'direction' : Direction,
        'tradeOrigin' : TradeOrigin,
        'duringTradeEmotion' : [] | [EmotionalSnapshot],
        'confidenceRating' : bigint,
        'originSourceNote' : [] | [string],
        'positionSize' : number,
        'isDraft' : boolean,
        'preTradeThesis' : PreTradeThesis,
        'realizedPnl' : [] | [number],
        'entryPrice' : number,
        'preSessionEmotion' : EmotionalSnapshot,
        'exitPrice' : [] | [number],
        'symbol' : string,
        'outcomeReasoning' : [] | [string],
      },
    ],
    bigint
  >,
  'deleteMedia' : ActorMethod<[bigint, bigint], boolean>,
  'deleteTrade' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'generateApiToken' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySummary' : ActorMethod<[bigint], Array<DailyTradeSummary>>,
  'getMonthlyConfidenceOutcome' : ActorMethod<
    [bigint, bigint],
    ConfidenceOutcomeAnalysis
  >,
  'getMonthlyFomoAnalysis' : ActorMethod<
    [bigint, bigint],
    {
      'fomoTaggedTradeIds' : Array<bigint>,
      'skippedTrades' : Array<SkippedTrade>,
      'theoreticalPnlTotal' : number,
    }
  >,
  'getMonthlyHoldTimeAnalysis' : ActorMethod<
    [bigint, bigint],
    HoldTimeAnalysis
  >,
  'getMonthlyStrategyBaseline' : ActorMethod<
    [bigint, bigint],
    StrategyBaselineAnalysis
  >,
  'getSelfAssessment' : ActorMethod<[], SelfAssessment>,
  'getTargetedFixes' : ActorMethod<
    [Array<BiasSignatureType>],
    Array<TargetedFix>
  >,
  'getTrade' : ActorMethod<[bigint], [] | [Trade]>,
  'getWeeklySignatures' : ActorMethod<[bigint, bigint], Array<BiasSignature>>,
  'hasApiToken' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAudioRecapsForTrade' : ActorMethod<[bigint], Array<AudioRecap>>,
  'listMediaForTrade' : ActorMethod<[bigint], Array<Media>>,
  'listSkippedTrades' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'items' : Array<SkippedTrade> }
  >,
  'listTrades' : ActorMethod<
    [TradeListFilter, bigint, bigint],
    { 'total' : bigint, 'items' : Array<Trade> }
  >,
  'receiveExtensionCapture' : ActorMethod<[ExtensionCapture], CaptureResult>,
  'regenerateApiToken' : ActorMethod<[], string>,
  'schema' : ActorMethod<[], string>,
  'updateTrade' : ActorMethod<
    [
      bigint,
      {
        'exitAtNs' : [] | [bigint],
        'duringTradeEmotion' : [] | [EmotionalSnapshot],
        'confidenceRating' : [] | [bigint],
        'isDraft' : [] | [boolean],
        'realizedPnl' : [] | [number],
        'exitPrice' : [] | [number],
        'outcomeReasoning' : [] | [string],
      },
    ],
    Trade
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];