/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface CounterReason {
    text: string;
}
export interface BiasSignature {
    tradeIds: Array<bigint>;
    type: BiasSignatureType;
    description: string;
}
export interface TargetedFix {
    type: BiasSignatureType;
    suggestion: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BiasCategoryCount {
    count: bigint;
    type: BiasSignatureType;
    preventableLossEstimate: number;
}
export interface TradeListFilter {
    sortBy: Variant_dateAsc_pnlAsc_pnlDesc_dateDesc;
    dateFromNs?: bigint;
    emotionalState?: EmotionalState;
    symbolQuery?: string;
    dateToNs?: bigint;
    originTag?: TradeOrigin;
}
export interface ConfidenceOutcomeAnalysis {
    overconfidenceFlag: boolean;
    correlation: number;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Media {
    id: bigint;
    uploadedAtNs: bigint;
    source: Variant_userUpload_chromeExtension;
    tradeId: bigint;
    originalStorageKey?: string;
    storageKey: string;
    caption?: string;
    mediaType: MediaType;
    chartMetadata?: ChartMetadata;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface SkippedTrade {
    id: bigint;
    skippedAtNs: bigint;
    fomoTagged: boolean;
    owner: Principal;
    note: string;
    theoreticalPnl?: number;
    symbol: string;
}
export interface StrategyBaselineAnalysis {
    statusQuoBiasFlag: boolean;
    historicalWinRate?: number;
    winRate: number;
    historicalProfitFactor?: number;
    profitFactor: number;
}
export interface HoldTimeAnalysis {
    avgLoserHoldSecs?: bigint;
    avgWinnerHoldSecs?: bigint;
    lossAversionFlag: boolean;
}
export interface PreTradeThesis {
    thesis: string;
    counterReasons: Array<CounterReason>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    id: bigint;
    exitAtNs?: bigint;
    entryAtNs: bigint;
    direction: Direction;
    updatedAtNs: bigint;
    tradeOrigin: TradeOrigin;
    owner: Principal;
    createdAtNs: bigint;
    duringTradeEmotion?: EmotionalSnapshot;
    confidenceRating: bigint;
    originSourceNote?: string;
    positionSize: number;
    isDraft: boolean;
    preTradeThesis: PreTradeThesis;
    realizedPnl?: number;
    shareableUrl?: string;
    entryPrice: number;
    preSessionEmotion: EmotionalSnapshot;
    exitPrice?: number;
    holdTimeSecs?: bigint;
    symbol: string;
    outcomeReasoning?: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface DailyTradeSummary {
    direction: Direction;
    enteredAtNs: bigint;
    confidenceRating: bigint;
    bearCasePresent: boolean;
    tradeId: bigint;
    realizedPnl?: number;
    symbol: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface CaptureResult {
    tradeId: bigint;
    wasDraftCreated: boolean;
    mediaId: bigint;
}
export interface ExtensionCapture {
    direction?: Direction;
    token: string;
    timeframe?: string;
    outcomeNotes?: string;
    size?: number;
    realizedPnl?: number;
    caption?: string;
    mediaType: MediaType;
    entryPrice?: number;
    targetTradeId?: bigint;
    price?: number;
    exitPrice?: number;
    mediaStorageKey: string;
    symbol?: string;
}
export interface EmotionalSnapshot {
    note: string;
    state: EmotionalState;
    capturedAtNs: bigint;
}
export interface SelfAssessment {
    categorizedTrades: Array<BiasCategoryCount>;
    topBiases: Array<BiasSignatureType>;
    progressTo20: bigint;
    progressTo50: bigint;
}
export interface ChartMetadata {
    timeframe?: string;
    price?: number;
    symbol?: string;
}
export interface AudioRecap {
    id: bigint;
    durationSecs: bigint;
    audioStorageKey: string;
    tradeId: bigint;
    recordedAtNs: bigint;
    transcript: string;
}
export enum BiasSignatureType {
    confirmationBias = "confirmationBias",
    herdMentality = "herdMentality",
    statusQuoBias = "statusQuoBias",
    dispositionEffect = "dispositionEffect",
    fomoRegret = "fomoRegret",
    overconfidence = "overconfidence",
    lossAversion = "lossAversion",
    hotHandFallacy = "hotHandFallacy"
}
export enum Direction {
    long_ = "long",
    short_ = "short"
}
export enum EmotionalState {
    greedy = "greedy",
    fearful = "fearful",
    anxious = "anxious",
    calm = "calm",
    euphoric = "euphoric",
    neutral = "neutral"
}
export enum MediaType {
    gif = "gif",
    videoClip = "videoClip",
    annotatedImage = "annotatedImage",
    screenshot = "screenshot"
}
export enum TradeOrigin {
    sociallyInfluenced = "sociallyInfluenced",
    selfGenerated = "selfGenerated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_dateAsc_pnlAsc_pnlDesc_dateDesc {
    dateAsc = "dateAsc",
    pnlAsc = "pnlAsc",
    pnlDesc = "pnlDesc",
    dateDesc = "dateDesc"
}
export enum Variant_userUpload_chromeExtension {
    userUpload = "userUpload",
    chromeExtension = "chromeExtension"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addAudioRecapToTrade(tradeId: bigint, recap: {
        durationSecs: bigint;
        audioStorageKey: string;
        transcript: string;
    }): Promise<AudioRecap>;
    addMediaToTrade(tradeId: bigint, media: {
        originalStorageKey?: string;
        storageKey: string;
        caption?: string;
        mediaType: MediaType;
        chartMetadata?: ChartMetadata;
    }): Promise<Media>;
    addSkippedTrade(input: {
        fomoTagged: boolean;
        note: string;
        theoreticalPnl?: number;
        symbol: string;
    }): Promise<SkippedTrade>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTrade(input: {
        exitAtNs?: bigint;
        entryAtNs: bigint;
        direction: Direction;
        tradeOrigin: TradeOrigin;
        duringTradeEmotion?: EmotionalSnapshot;
        confidenceRating: bigint;
        originSourceNote?: string;
        positionSize: number;
        isDraft: boolean;
        preTradeThesis: PreTradeThesis;
        realizedPnl?: number;
        entryPrice: number;
        preSessionEmotion: EmotionalSnapshot;
        exitPrice?: number;
        symbol: string;
        outcomeReasoning?: string;
    }): Promise<bigint>;
    deleteMedia(tradeId: bigint, mediaId: bigint): Promise<boolean>;
    deleteTrade(tradeId: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    generateApiToken(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getDailySummary(dayStartNs: bigint): Promise<Array<DailyTradeSummary>>;
    getMonthlyConfidenceOutcome(monthStartNs: bigint, monthEndNs: bigint): Promise<ConfidenceOutcomeAnalysis>;
    getMonthlyFomoAnalysis(monthStartNs: bigint, monthEndNs: bigint): Promise<{
        fomoTaggedTradeIds: Array<bigint>;
        skippedTrades: Array<SkippedTrade>;
        theoreticalPnlTotal: number;
    }>;
    getMonthlyHoldTimeAnalysis(monthStartNs: bigint, monthEndNs: bigint): Promise<HoldTimeAnalysis>;
    getMonthlyStrategyBaseline(monthStartNs: bigint, monthEndNs: bigint): Promise<StrategyBaselineAnalysis>;
    getSelfAssessment(): Promise<SelfAssessment>;
    getTargetedFixes(biasTypes: Array<BiasSignatureType>): Promise<Array<TargetedFix>>;
    getTrade(tradeId: bigint): Promise<Trade | null>;
    getWeeklySignatures(weekStartNs: bigint, weekEndNs: bigint): Promise<Array<BiasSignature>>;
    hasApiToken(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAudioRecapsForTrade(tradeId: bigint): Promise<Array<AudioRecap>>;
    listMediaForTrade(tradeId: bigint): Promise<Array<Media>>;
    listSkippedTrades(limit: bigint, offset: bigint): Promise<{
        total: bigint;
        items: Array<SkippedTrade>;
    }>;
    listTrades(filter: TradeListFilter, limit: bigint, offset: bigint): Promise<{
        total: bigint;
        items: Array<Trade>;
    }>;
    receiveExtensionCapture(capture: ExtensionCapture): Promise<CaptureResult>;
    regenerateApiToken(): Promise<string>;
    schema(): Promise<string>;
    updateTrade(tradeId: bigint, updates: {
        exitAtNs?: bigint;
        duringTradeEmotion?: EmotionalSnapshot;
        confidenceRating?: bigint;
        isDraft?: boolean;
        realizedPnl?: number;
        exitPrice?: number;
        outcomeReasoning?: string;
    }): Promise<Trade>;
}
import type { BiasCategoryCount as _BiasCategoryCount, BiasSignature as _BiasSignature, BiasSignatureType as _BiasSignatureType, Cell as _Cell, ChartMetadata as _ChartMetadata, DailyTradeSummary as _DailyTradeSummary, Direction as _Direction, EmotionalSnapshot as _EmotionalSnapshot, EmotionalState as _EmotionalState, Error as _Error, ExtensionCapture as _ExtensionCapture, HoldTimeAnalysis as _HoldTimeAnalysis, Media as _Media, MediaType as _MediaType, PreTradeThesis as _PreTradeThesis, Result as _Result, Result__1 as _Result__1, SelfAssessment as _SelfAssessment, SkippedTrade as _SkippedTrade, StrategyBaselineAnalysis as _StrategyBaselineAnalysis, TargetedFix as _TargetedFix, Trade as _Trade, TradeListFilter as _TradeListFilter, TradeOrigin as _TradeOrigin, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAudioRecapToTrade(arg0: bigint, arg1: {
        durationSecs: bigint;
        audioStorageKey: string;
        transcript: string;
    }): Promise<AudioRecap> {
        if (this.processError) {
            try {
                const result = await this.actor.addAudioRecapToTrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAudioRecapToTrade(arg0, arg1);
            return result;
        }
    }
    async addMediaToTrade(arg0: bigint, arg1: {
        originalStorageKey?: string;
        storageKey: string;
        caption?: string;
        mediaType: MediaType;
        chartMetadata?: ChartMetadata;
    }): Promise<Media> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaToTrade(arg0, to_candid_record_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Media_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaToTrade(arg0, to_candid_record_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Media_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSkippedTrade(arg0: {
        fomoTagged: boolean;
        note: string;
        theoreticalPnl?: number;
        symbol: string;
    }): Promise<SkippedTrade> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkippedTrade(to_candid_record_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SkippedTrade_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkippedTrade(to_candid_record_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SkippedTrade_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTrade(arg0: {
        exitAtNs?: bigint;
        entryAtNs: bigint;
        direction: Direction;
        tradeOrigin: TradeOrigin;
        duringTradeEmotion?: EmotionalSnapshot;
        confidenceRating: bigint;
        originSourceNote?: string;
        positionSize: number;
        isDraft: boolean;
        preTradeThesis: PreTradeThesis;
        realizedPnl?: number;
        entryPrice: number;
        preSessionEmotion: EmotionalSnapshot;
        exitPrice?: number;
        symbol: string;
        outcomeReasoning?: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(to_candid_record_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(to_candid_record_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMedia(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0, arg1);
            return result;
        }
    }
    async deleteTrade(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateApiToken(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiToken();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySummary(arg0: bigint): Promise<Array<DailyTradeSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyConfidenceOutcome(arg0: bigint, arg1: bigint): Promise<ConfidenceOutcomeAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyConfidenceOutcome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyConfidenceOutcome(arg0, arg1);
            return result;
        }
    }
    async getMonthlyFomoAnalysis(arg0: bigint, arg1: bigint): Promise<{
        fomoTaggedTradeIds: Array<bigint>;
        skippedTrades: Array<SkippedTrade>;
        theoreticalPnlTotal: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyFomoAnalysis(arg0, arg1);
                return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyFomoAnalysis(arg0, arg1);
            return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyHoldTimeAnalysis(arg0: bigint, arg1: bigint): Promise<HoldTimeAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyHoldTimeAnalysis(arg0, arg1);
                return from_candid_HoldTimeAnalysis_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyHoldTimeAnalysis(arg0, arg1);
            return from_candid_HoldTimeAnalysis_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyStrategyBaseline(arg0: bigint, arg1: bigint): Promise<StrategyBaselineAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyStrategyBaseline(arg0, arg1);
                return from_candid_StrategyBaselineAnalysis_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyStrategyBaseline(arg0, arg1);
            return from_candid_StrategyBaselineAnalysis_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSelfAssessment(): Promise<SelfAssessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelfAssessment();
                return from_candid_SelfAssessment_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelfAssessment();
            return from_candid_SelfAssessment_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTargetedFixes(arg0: Array<BiasSignatureType>): Promise<Array<TargetedFix>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTargetedFixes(to_candid_vec_n70(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTargetedFixes(to_candid_vec_n70(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: bigint): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySignatures(arg0: bigint, arg1: bigint): Promise<Array<BiasSignature>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySignatures(arg0, arg1);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySignatures(arg0, arg1);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasApiToken(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasApiToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasApiToken();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAudioRecapsForTrade(arg0: bigint): Promise<Array<AudioRecap>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAudioRecapsForTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAudioRecapsForTrade(arg0);
            return result;
        }
    }
    async listMediaForTrade(arg0: bigint): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMediaForTrade(arg0);
                return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMediaForTrade(arg0);
            return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSkippedTrades(arg0: bigint, arg1: bigint): Promise<{
        total: bigint;
        items: Array<SkippedTrade>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listSkippedTrades(arg0, arg1);
                return from_candid_record_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSkippedTrades(arg0, arg1);
            return from_candid_record_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrades(arg0: TradeListFilter, arg1: bigint, arg2: bigint): Promise<{
        total: bigint;
        items: Array<Trade>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrades(to_candid_TradeListFilter_n92(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_record_n95(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrades(to_candid_TradeListFilter_n92(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_record_n95(this._uploadFile, this._downloadFile, result);
        }
    }
    async receiveExtensionCapture(arg0: ExtensionCapture): Promise<CaptureResult> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveExtensionCapture(to_candid_ExtensionCapture_n97(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveExtensionCapture(to_candid_ExtensionCapture_n97(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async regenerateApiToken(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateApiToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateApiToken();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateTrade(arg0: bigint, arg1: {
        exitAtNs?: bigint;
        duringTradeEmotion?: EmotionalSnapshot;
        confidenceRating?: bigint;
        isDraft?: boolean;
        realizedPnl?: number;
        exitPrice?: number;
        outcomeReasoning?: string;
    }): Promise<Trade> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, to_candid_record_n99(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Trade_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, to_candid_record_n99(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Trade_n77(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BiasCategoryCount_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BiasCategoryCount): BiasCategoryCount {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_BiasSignatureType_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BiasSignatureType): BiasSignatureType {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_BiasSignature_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BiasSignature): BiasSignature {
    return from_candid_record_n89(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ChartMetadata_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartMetadata): ChartMetadata {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DailyTradeSummary_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyTradeSummary): DailyTradeSummary {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionalSnapshot_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionalSnapshot): EmotionalSnapshot {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionalState_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionalState): EmotionalState {
    return from_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HoldTimeAnalysis_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HoldTimeAnalysis): HoldTimeAnalysis {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Media_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Media {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_SelfAssessment_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SelfAssessment): SelfAssessment {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_SkippedTrade_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkippedTrade): SkippedTrade {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_StrategyBaselineAnalysis_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrategyBaselineAnalysis): StrategyBaselineAnalysis {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_TargetedFix_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TargetedFix): TargetedFix {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOrigin_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOrigin): TradeOrigin {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChartMetadata]): ChartMetadata | null {
    return value.length === 0 ? null : from_candid_ChartMetadata_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trade]): Trade | null {
    return value.length === 0 ? null : from_candid_Trade_n77(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmotionalSnapshot]): EmotionalSnapshot | null {
    return value.length === 0 ? null : from_candid_EmotionalSnapshot_n83(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    uploadedAtNs: bigint;
    source: {
        userUpload: null;
    } | {
        chromeExtension: null;
    };
    tradeId: bigint;
    originalStorageKey: [] | [string];
    storageKey: string;
    caption: [] | [string];
    mediaType: _MediaType;
    chartMetadata: [] | [_ChartMetadata];
}): {
    id: bigint;
    uploadedAtNs: bigint;
    source: Variant_userUpload_chromeExtension;
    tradeId: bigint;
    originalStorageKey?: string;
    storageKey: string;
    caption?: string;
    mediaType: MediaType;
    chartMetadata?: ChartMetadata;
} {
    return {
        id: value.id,
        uploadedAtNs: value.uploadedAtNs,
        source: from_candid_variant_n19(_uploadFile, _downloadFile, value.source),
        tradeId: value.tradeId,
        originalStorageKey: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.originalStorageKey)),
        storageKey: value.storageKey,
        caption: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.caption)),
        mediaType: from_candid_MediaType_n21(_uploadFile, _downloadFile, value.mediaType),
        chartMetadata: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.chartMetadata))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeframe: [] | [string];
    price: [] | [number];
    symbol: [] | [string];
}): {
    timeframe?: string;
    price?: number;
    symbol?: string;
} {
    return {
        timeframe: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.timeframe)),
        price: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.price)),
        symbol: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.symbol))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    skippedAtNs: bigint;
    fomoTagged: boolean;
    owner: Principal;
    note: string;
    theoreticalPnl: [] | [number];
    symbol: string;
}): {
    id: bigint;
    skippedAtNs: bigint;
    fomoTagged: boolean;
    owner: Principal;
    note: string;
    theoreticalPnl?: number;
    symbol: string;
} {
    return {
        id: value.id,
        skippedAtNs: value.skippedAtNs,
        fomoTagged: value.fomoTagged,
        owner: value.owner,
        note: value.note,
        theoreticalPnl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.theoreticalPnl)),
        symbol: value.symbol
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n43(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n47(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
    enteredAtNs: bigint;
    confidenceRating: bigint;
    bearCasePresent: boolean;
    tradeId: bigint;
    realizedPnl: [] | [number];
    symbol: string;
}): {
    direction: Direction;
    enteredAtNs: bigint;
    confidenceRating: bigint;
    bearCasePresent: boolean;
    tradeId: bigint;
    realizedPnl?: number;
    symbol: string;
} {
    return {
        direction: from_candid_Direction_n54(_uploadFile, _downloadFile, value.direction),
        enteredAtNs: value.enteredAtNs,
        confidenceRating: value.confidenceRating,
        bearCasePresent: value.bearCasePresent,
        tradeId: value.tradeId,
        realizedPnl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.realizedPnl)),
        symbol: value.symbol
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fomoTaggedTradeIds: Array<bigint>;
    skippedTrades: Array<_SkippedTrade>;
    theoreticalPnlTotal: number;
}): {
    fomoTaggedTradeIds: Array<bigint>;
    skippedTrades: Array<SkippedTrade>;
    theoreticalPnlTotal: number;
} {
    return {
        fomoTaggedTradeIds: value.fomoTaggedTradeIds,
        skippedTrades: from_candid_vec_n57(_uploadFile, _downloadFile, value.skippedTrades),
        theoreticalPnlTotal: value.theoreticalPnlTotal
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avgLoserHoldSecs: [] | [bigint];
    avgWinnerHoldSecs: [] | [bigint];
    lossAversionFlag: boolean;
}): {
    avgLoserHoldSecs?: bigint;
    avgWinnerHoldSecs?: bigint;
    lossAversionFlag: boolean;
} {
    return {
        avgLoserHoldSecs: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avgLoserHoldSecs)),
        avgWinnerHoldSecs: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avgWinnerHoldSecs)),
        lossAversionFlag: value.lossAversionFlag
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statusQuoBiasFlag: boolean;
    historicalWinRate: [] | [number];
    winRate: number;
    historicalProfitFactor: [] | [number];
    profitFactor: number;
}): {
    statusQuoBiasFlag: boolean;
    historicalWinRate?: number;
    winRate: number;
    historicalProfitFactor?: number;
    profitFactor: number;
} {
    return {
        statusQuoBiasFlag: value.statusQuoBiasFlag,
        historicalWinRate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.historicalWinRate)),
        winRate: value.winRate,
        historicalProfitFactor: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.historicalProfitFactor)),
        profitFactor: value.profitFactor
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categorizedTrades: Array<_BiasCategoryCount>;
    topBiases: Array<_BiasSignatureType>;
    progressTo20: bigint;
    progressTo50: bigint;
}): {
    categorizedTrades: Array<BiasCategoryCount>;
    topBiases: Array<BiasSignatureType>;
    progressTo20: bigint;
    progressTo50: bigint;
} {
    return {
        categorizedTrades: from_candid_vec_n64(_uploadFile, _downloadFile, value.categorizedTrades),
        topBiases: from_candid_vec_n69(_uploadFile, _downloadFile, value.topBiases),
        progressTo20: value.progressTo20,
        progressTo50: value.progressTo50
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    type: _BiasSignatureType;
    preventableLossEstimate: number;
}): {
    count: bigint;
    type: BiasSignatureType;
    preventableLossEstimate: number;
} {
    return {
        count: value.count,
        type: from_candid_BiasSignatureType_n67(_uploadFile, _downloadFile, value.type),
        preventableLossEstimate: value.preventableLossEstimate
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type: _BiasSignatureType;
    suggestion: string;
}): {
    type: BiasSignatureType;
    suggestion: string;
} {
    return {
        type: from_candid_BiasSignatureType_n67(_uploadFile, _downloadFile, value.type),
        suggestion: value.suggestion
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exitAtNs: [] | [bigint];
    entryAtNs: bigint;
    direction: _Direction;
    updatedAtNs: bigint;
    tradeOrigin: _TradeOrigin;
    owner: Principal;
    createdAtNs: bigint;
    duringTradeEmotion: [] | [_EmotionalSnapshot];
    confidenceRating: bigint;
    originSourceNote: [] | [string];
    positionSize: number;
    isDraft: boolean;
    preTradeThesis: _PreTradeThesis;
    realizedPnl: [] | [number];
    shareableUrl: [] | [string];
    entryPrice: number;
    preSessionEmotion: _EmotionalSnapshot;
    exitPrice: [] | [number];
    holdTimeSecs: [] | [bigint];
    symbol: string;
    outcomeReasoning: [] | [string];
}): {
    id: bigint;
    exitAtNs?: bigint;
    entryAtNs: bigint;
    direction: Direction;
    updatedAtNs: bigint;
    tradeOrigin: TradeOrigin;
    owner: Principal;
    createdAtNs: bigint;
    duringTradeEmotion?: EmotionalSnapshot;
    confidenceRating: bigint;
    originSourceNote?: string;
    positionSize: number;
    isDraft: boolean;
    preTradeThesis: PreTradeThesis;
    realizedPnl?: number;
    shareableUrl?: string;
    entryPrice: number;
    preSessionEmotion: EmotionalSnapshot;
    exitPrice?: number;
    holdTimeSecs?: bigint;
    symbol: string;
    outcomeReasoning?: string;
} {
    return {
        id: value.id,
        exitAtNs: record_opt_to_undefined(from_candid_opt_n79(_uploadFile, _downloadFile, value.exitAtNs)),
        entryAtNs: value.entryAtNs,
        direction: from_candid_Direction_n54(_uploadFile, _downloadFile, value.direction),
        updatedAtNs: value.updatedAtNs,
        tradeOrigin: from_candid_TradeOrigin_n80(_uploadFile, _downloadFile, value.tradeOrigin),
        owner: value.owner,
        createdAtNs: value.createdAtNs,
        duringTradeEmotion: record_opt_to_undefined(from_candid_opt_n82(_uploadFile, _downloadFile, value.duringTradeEmotion)),
        confidenceRating: value.confidenceRating,
        originSourceNote: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.originSourceNote)),
        positionSize: value.positionSize,
        isDraft: value.isDraft,
        preTradeThesis: value.preTradeThesis,
        realizedPnl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.realizedPnl)),
        shareableUrl: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.shareableUrl)),
        entryPrice: value.entryPrice,
        preSessionEmotion: from_candid_EmotionalSnapshot_n83(_uploadFile, _downloadFile, value.preSessionEmotion),
        exitPrice: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.exitPrice)),
        holdTimeSecs: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.holdTimeSecs)),
        symbol: value.symbol,
        outcomeReasoning: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.outcomeReasoning))
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note: string;
    state: _EmotionalState;
    capturedAtNs: bigint;
}): {
    note: string;
    state: EmotionalState;
    capturedAtNs: bigint;
} {
    return {
        note: value.note,
        state: from_candid_EmotionalState_n85(_uploadFile, _downloadFile, value.state),
        capturedAtNs: value.capturedAtNs
    };
}
function from_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeIds: Array<bigint>;
    type: _BiasSignatureType;
    description: string;
}): {
    tradeIds: Array<bigint>;
    type: BiasSignatureType;
    description: string;
} {
    return {
        tradeIds: value.tradeIds,
        type: from_candid_BiasSignatureType_n67(_uploadFile, _downloadFile, value.type),
        description: value.description
    };
}
function from_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_SkippedTrade>;
}): {
    total: bigint;
    items: Array<SkippedTrade>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n57(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_Trade>;
}): {
    total: bigint;
    items: Array<Trade>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n96(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userUpload: null;
} | {
    chromeExtension: null;
}): Variant_userUpload_chromeExtension {
    return "userUpload" in value ? Variant_userUpload_chromeExtension.userUpload : "chromeExtension" in value ? Variant_userUpload_chromeExtension.chromeExtension : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gif: null;
} | {
    videoClip: null;
} | {
    annotatedImage: null;
} | {
    screenshot: null;
}): MediaType {
    return "gif" in value ? MediaType.gif : "videoClip" in value ? MediaType.videoClip : "annotatedImage" in value ? MediaType.annotatedImage : "screenshot" in value ? MediaType.screenshot : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): Direction {
    return "long" in value ? Direction.long : "short" in value ? Direction.short : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    confirmationBias: null;
} | {
    herdMentality: null;
} | {
    statusQuoBias: null;
} | {
    dispositionEffect: null;
} | {
    fomoRegret: null;
} | {
    overconfidence: null;
} | {
    lossAversion: null;
} | {
    hotHandFallacy: null;
}): BiasSignatureType {
    return "confirmationBias" in value ? BiasSignatureType.confirmationBias : "herdMentality" in value ? BiasSignatureType.herdMentality : "statusQuoBias" in value ? BiasSignatureType.statusQuoBias : "dispositionEffect" in value ? BiasSignatureType.dispositionEffect : "fomoRegret" in value ? BiasSignatureType.fomoRegret : "overconfidence" in value ? BiasSignatureType.overconfidence : "lossAversion" in value ? BiasSignatureType.lossAversion : "hotHandFallacy" in value ? BiasSignatureType.hotHandFallacy : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sociallyInfluenced: null;
} | {
    selfGenerated: null;
}): TradeOrigin {
    return "sociallyInfluenced" in value ? TradeOrigin.sociallyInfluenced : "selfGenerated" in value ? TradeOrigin.selfGenerated : value;
}
function from_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    greedy: null;
} | {
    fearful: null;
} | {
    anxious: null;
} | {
    calm: null;
} | {
    euphoric: null;
} | {
    neutral: null;
}): EmotionalState {
    return "greedy" in value ? EmotionalState.greedy : "fearful" in value ? EmotionalState.fearful : "anxious" in value ? EmotionalState.anxious : "calm" in value ? EmotionalState.calm : "euphoric" in value ? EmotionalState.euphoric : "neutral" in value ? EmotionalState.neutral : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyTradeSummary>): Array<DailyTradeSummary> {
    return value.map((x)=>from_candid_DailyTradeSummary_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkippedTrade>): Array<SkippedTrade> {
    return value.map((x)=>from_candid_SkippedTrade_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BiasCategoryCount>): Array<BiasCategoryCount> {
    return value.map((x)=>from_candid_BiasCategoryCount_n65(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BiasSignatureType>): Array<BiasSignatureType> {
    return value.map((x)=>from_candid_BiasSignatureType_n67(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TargetedFix>): Array<TargetedFix> {
    return value.map((x)=>from_candid_TargetedFix_n74(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BiasSignature>): Array<BiasSignature> {
    return value.map((x)=>from_candid_BiasSignature_n88(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Array<Media> {
    return value.map((x)=>from_candid_Media_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n77(_uploadFile, _downloadFile, x));
}
function to_candid_BiasSignatureType_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiasSignatureType): _BiasSignatureType {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_ChartMetadata_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartMetadata): _ChartMetadata {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionalSnapshot_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalSnapshot): _EmotionalSnapshot {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionalState_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalState): _EmotionalState {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_ExtensionCapture_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtensionCapture): _ExtensionCapture {
    return to_candid_record_n98(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TradeListFilter_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeListFilter): _TradeListFilter {
    return to_candid_record_n93(_uploadFile, _downloadFile, value);
}
function to_candid_TradeOrigin_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeOrigin): _TradeOrigin {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalStorageKey?: string;
    storageKey: string;
    caption?: string;
    mediaType: MediaType;
    chartMetadata?: ChartMetadata;
}): {
    originalStorageKey: [] | [string];
    storageKey: string;
    caption: [] | [string];
    mediaType: _MediaType;
    chartMetadata: [] | [_ChartMetadata];
} {
    return {
        originalStorageKey: value.originalStorageKey ? candid_some(value.originalStorageKey) : candid_none(),
        storageKey: value.storageKey,
        caption: value.caption ? candid_some(value.caption) : candid_none(),
        mediaType: to_candid_MediaType_n13(_uploadFile, _downloadFile, value.mediaType),
        chartMetadata: value.chartMetadata ? candid_some(to_candid_ChartMetadata_n15(_uploadFile, _downloadFile, value.chartMetadata)) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeframe?: string;
    price?: number;
    symbol?: string;
}): {
    timeframe: [] | [string];
    price: [] | [number];
    symbol: [] | [string];
} {
    return {
        timeframe: value.timeframe ? candid_some(value.timeframe) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        symbol: value.symbol ? candid_some(value.symbol) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fomoTagged: boolean;
    note: string;
    theoreticalPnl?: number;
    symbol: string;
}): {
    fomoTagged: boolean;
    note: string;
    theoreticalPnl: [] | [number];
    symbol: string;
} {
    return {
        fomoTagged: value.fomoTagged,
        note: value.note,
        theoreticalPnl: value.theoreticalPnl ? candid_some(value.theoreticalPnl) : candid_none(),
        symbol: value.symbol
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exitAtNs?: bigint;
    entryAtNs: bigint;
    direction: Direction;
    tradeOrigin: TradeOrigin;
    duringTradeEmotion?: EmotionalSnapshot;
    confidenceRating: bigint;
    originSourceNote?: string;
    positionSize: number;
    isDraft: boolean;
    preTradeThesis: PreTradeThesis;
    realizedPnl?: number;
    entryPrice: number;
    preSessionEmotion: EmotionalSnapshot;
    exitPrice?: number;
    symbol: string;
    outcomeReasoning?: string;
}): {
    exitAtNs: [] | [bigint];
    entryAtNs: bigint;
    direction: _Direction;
    tradeOrigin: _TradeOrigin;
    duringTradeEmotion: [] | [_EmotionalSnapshot];
    confidenceRating: bigint;
    originSourceNote: [] | [string];
    positionSize: number;
    isDraft: boolean;
    preTradeThesis: _PreTradeThesis;
    realizedPnl: [] | [number];
    entryPrice: number;
    preSessionEmotion: _EmotionalSnapshot;
    exitPrice: [] | [number];
    symbol: string;
    outcomeReasoning: [] | [string];
} {
    return {
        exitAtNs: value.exitAtNs ? candid_some(value.exitAtNs) : candid_none(),
        entryAtNs: value.entryAtNs,
        direction: to_candid_Direction_n33(_uploadFile, _downloadFile, value.direction),
        tradeOrigin: to_candid_TradeOrigin_n35(_uploadFile, _downloadFile, value.tradeOrigin),
        duringTradeEmotion: value.duringTradeEmotion ? candid_some(to_candid_EmotionalSnapshot_n37(_uploadFile, _downloadFile, value.duringTradeEmotion)) : candid_none(),
        confidenceRating: value.confidenceRating,
        originSourceNote: value.originSourceNote ? candid_some(value.originSourceNote) : candid_none(),
        positionSize: value.positionSize,
        isDraft: value.isDraft,
        preTradeThesis: value.preTradeThesis,
        realizedPnl: value.realizedPnl ? candid_some(value.realizedPnl) : candid_none(),
        entryPrice: value.entryPrice,
        preSessionEmotion: to_candid_EmotionalSnapshot_n37(_uploadFile, _downloadFile, value.preSessionEmotion),
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none(),
        symbol: value.symbol,
        outcomeReasoning: value.outcomeReasoning ? candid_some(value.outcomeReasoning) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note: string;
    state: EmotionalState;
    capturedAtNs: bigint;
}): {
    note: string;
    state: _EmotionalState;
    capturedAtNs: bigint;
} {
    return {
        note: value.note,
        state: to_candid_EmotionalState_n39(_uploadFile, _downloadFile, value.state),
        capturedAtNs: value.capturedAtNs
    };
}
function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy: Variant_dateAsc_pnlAsc_pnlDesc_dateDesc;
    dateFromNs?: bigint;
    emotionalState?: EmotionalState;
    symbolQuery?: string;
    dateToNs?: bigint;
    originTag?: TradeOrigin;
}): {
    sortBy: {
        dateAsc: null;
    } | {
        pnlAsc: null;
    } | {
        pnlDesc: null;
    } | {
        dateDesc: null;
    };
    dateFromNs: [] | [bigint];
    emotionalState: [] | [_EmotionalState];
    symbolQuery: [] | [string];
    dateToNs: [] | [bigint];
    originTag: [] | [_TradeOrigin];
} {
    return {
        sortBy: to_candid_variant_n94(_uploadFile, _downloadFile, value.sortBy),
        dateFromNs: value.dateFromNs ? candid_some(value.dateFromNs) : candid_none(),
        emotionalState: value.emotionalState ? candid_some(to_candid_EmotionalState_n39(_uploadFile, _downloadFile, value.emotionalState)) : candid_none(),
        symbolQuery: value.symbolQuery ? candid_some(value.symbolQuery) : candid_none(),
        dateToNs: value.dateToNs ? candid_some(value.dateToNs) : candid_none(),
        originTag: value.originTag ? candid_some(to_candid_TradeOrigin_n35(_uploadFile, _downloadFile, value.originTag)) : candid_none()
    };
}
function to_candid_record_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction?: Direction;
    token: string;
    timeframe?: string;
    outcomeNotes?: string;
    size?: number;
    realizedPnl?: number;
    caption?: string;
    mediaType: MediaType;
    entryPrice?: number;
    targetTradeId?: bigint;
    price?: number;
    exitPrice?: number;
    mediaStorageKey: string;
    symbol?: string;
}): {
    direction: [] | [_Direction];
    token: string;
    timeframe: [] | [string];
    outcomeNotes: [] | [string];
    size: [] | [number];
    realizedPnl: [] | [number];
    caption: [] | [string];
    mediaType: _MediaType;
    entryPrice: [] | [number];
    targetTradeId: [] | [bigint];
    price: [] | [number];
    exitPrice: [] | [number];
    mediaStorageKey: string;
    symbol: [] | [string];
} {
    return {
        direction: value.direction ? candid_some(to_candid_Direction_n33(_uploadFile, _downloadFile, value.direction)) : candid_none(),
        token: value.token,
        timeframe: value.timeframe ? candid_some(value.timeframe) : candid_none(),
        outcomeNotes: value.outcomeNotes ? candid_some(value.outcomeNotes) : candid_none(),
        size: value.size ? candid_some(value.size) : candid_none(),
        realizedPnl: value.realizedPnl ? candid_some(value.realizedPnl) : candid_none(),
        caption: value.caption ? candid_some(value.caption) : candid_none(),
        mediaType: to_candid_MediaType_n13(_uploadFile, _downloadFile, value.mediaType),
        entryPrice: value.entryPrice ? candid_some(value.entryPrice) : candid_none(),
        targetTradeId: value.targetTradeId ? candid_some(value.targetTradeId) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none(),
        mediaStorageKey: value.mediaStorageKey,
        symbol: value.symbol ? candid_some(value.symbol) : candid_none()
    };
}
function to_candid_record_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exitAtNs?: bigint;
    duringTradeEmotion?: EmotionalSnapshot;
    confidenceRating?: bigint;
    isDraft?: boolean;
    realizedPnl?: number;
    exitPrice?: number;
    outcomeReasoning?: string;
}): {
    exitAtNs: [] | [bigint];
    duringTradeEmotion: [] | [_EmotionalSnapshot];
    confidenceRating: [] | [bigint];
    isDraft: [] | [boolean];
    realizedPnl: [] | [number];
    exitPrice: [] | [number];
    outcomeReasoning: [] | [string];
} {
    return {
        exitAtNs: value.exitAtNs ? candid_some(value.exitAtNs) : candid_none(),
        duringTradeEmotion: value.duringTradeEmotion ? candid_some(to_candid_EmotionalSnapshot_n37(_uploadFile, _downloadFile, value.duringTradeEmotion)) : candid_none(),
        confidenceRating: value.confidenceRating ? candid_some(value.confidenceRating) : candid_none(),
        isDraft: value.isDraft ? candid_some(value.isDraft) : candid_none(),
        realizedPnl: value.realizedPnl ? candid_some(value.realizedPnl) : candid_none(),
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none(),
        outcomeReasoning: value.outcomeReasoning ? candid_some(value.outcomeReasoning) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    gif: null;
} | {
    videoClip: null;
} | {
    annotatedImage: null;
} | {
    screenshot: null;
} {
    return value == MediaType.gif ? {
        gif: null
    } : value == MediaType.videoClip ? {
        videoClip: null
    } : value == MediaType.annotatedImage ? {
        annotatedImage: null
    } : value == MediaType.screenshot ? {
        screenshot: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    long: null;
} | {
    short: null;
} {
    return value == Direction.long ? {
        long_: null
    } : value == Direction.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeOrigin): {
    sociallyInfluenced: null;
} | {
    selfGenerated: null;
} {
    return value == TradeOrigin.sociallyInfluenced ? {
        sociallyInfluenced: null
    } : value == TradeOrigin.selfGenerated ? {
        selfGenerated: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalState): {
    greedy: null;
} | {
    fearful: null;
} | {
    anxious: null;
} | {
    calm: null;
} | {
    euphoric: null;
} | {
    neutral: null;
} {
    return value == EmotionalState.greedy ? {
        greedy: null
    } : value == EmotionalState.fearful ? {
        fearful: null
    } : value == EmotionalState.anxious ? {
        anxious: null
    } : value == EmotionalState.calm ? {
        calm: null
    } : value == EmotionalState.euphoric ? {
        euphoric: null
    } : value == EmotionalState.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiasSignatureType): {
    confirmationBias: null;
} | {
    herdMentality: null;
} | {
    statusQuoBias: null;
} | {
    dispositionEffect: null;
} | {
    fomoRegret: null;
} | {
    overconfidence: null;
} | {
    lossAversion: null;
} | {
    hotHandFallacy: null;
} {
    return value == BiasSignatureType.confirmationBias ? {
        confirmationBias: null
    } : value == BiasSignatureType.herdMentality ? {
        herdMentality: null
    } : value == BiasSignatureType.statusQuoBias ? {
        statusQuoBias: null
    } : value == BiasSignatureType.dispositionEffect ? {
        dispositionEffect: null
    } : value == BiasSignatureType.fomoRegret ? {
        fomoRegret: null
    } : value == BiasSignatureType.overconfidence ? {
        overconfidence: null
    } : value == BiasSignatureType.lossAversion ? {
        lossAversion: null
    } : value == BiasSignatureType.hotHandFallacy ? {
        hotHandFallacy: null
    } : value;
}
function to_candid_variant_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dateAsc_pnlAsc_pnlDesc_dateDesc): {
    dateAsc: null;
} | {
    pnlAsc: null;
} | {
    pnlDesc: null;
} | {
    dateDesc: null;
} {
    return value == Variant_dateAsc_pnlAsc_pnlDesc_dateDesc.dateAsc ? {
        dateAsc: null
    } : value == Variant_dateAsc_pnlAsc_pnlDesc_dateDesc.pnlAsc ? {
        pnlAsc: null
    } : value == Variant_dateAsc_pnlAsc_pnlDesc_dateDesc.pnlDesc ? {
        pnlDesc: null
    } : value == Variant_dateAsc_pnlAsc_pnlDesc_dateDesc.dateDesc ? {
        dateDesc: null
    } : value;
}
function to_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BiasSignatureType>): Array<_BiasSignatureType> {
    return value.map((x)=>to_candid_BiasSignatureType_n71(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
